name: Checkout Code

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test path
        run: ls -la

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run index.js
        run: node index.js