// GitHub Actions workflow to checkout code
// Save this as .github/workflows/checkout.yml in your repo


name: Checkout Code

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4