name: Sonar Autofix Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.LLM_SECRET }}

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test path
        run: ls -la

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run index.js
        run: node index.js

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate random branch name
        id: gen_branch
        run: echo "branch_name=update-$(date +%s)-$RANDOM" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git checkout -b ${{ env.branch_name }}
          git add .
          git commit -m "Automated update from workflow"

      - name: Push changes
        run: |
          git push --set-upstream origin update-branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated update commit
          title: Automated Update PR
          body: This PR was created automatically by the workflow.
          base: main
          head: update-branch